stages:
  - stage: build_stage
    displayName: "Build"
    jobs:
      - job: build_job
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub'
            repository: 'lcars'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'